### ISSUE TITLE
Please add HDSkin to the OG-Name List

### ISSUE THREAD

**Issue by WaifuHub** [LabyMod/og-names#101]
Hey, so i was playing some LabyMod after a long time and i found out that there are now OG-Badges.
And since i own the account "HDSkin" i wanted to try applying for the badge.
I did recieve some offers for the name and was told it was rare.

Thats everything. Thank you and have a great day ^^

**Comment by yariquv3** [comment]
not og

**Comment by Dqnns** [comment]
Not "OG", sorry!
