### ISSUE TITLE
Add "Faler" to OG badge list!

### ISSUE THREAD

**Issue by ImRayvon** [LabyMod/og-names#102]
Hello, 

Sorry, I couldn’t open a pull request.

Sources: 
https://forebears.io/surnames/faler
https://www.houseofnames.com/faler-family-crest

Thank You!

**Comment by ImRayvon** [comment]
@Dqnns

**Comment by Dqnns** [comment]
Open a Pull Request! :)

[https://github.com/LabyMod/og-names/pulls](https://github.com/LabyMod/og-names/pulls)
[https://github.com/LabyMod/og-names/compare](https://github.com/LabyMod/og-names/compare)
