### ISSUE TITLE
Add "Objectivity" to OG Badge List

### ISSUE THREAD

**Issue by AutoSnipe** [LabyMod/og-names#104]
https://www.merriam-webster.com/dictionary/objectivity
https://www.merriam-webster.com/dictionary/objectivity
Hi,i think "Objectivity" is OG name
Have a good day

**Comment by AutoSnipe** [comment]
i don't know how to make a pull request?

**Comment by AutoSnipe** [comment]
i have made a pull request

**Comment by Dqnns** [comment]
#105
