### ISSUE TITLE
Add "Vaselia" to OG Badgelist

### ISSUE THREAD

**Issue by HazeWorksOnFiveMServer** [LabyMod/og-names#110]
It is an Greek Female Name and deserve like any other Name an OG Badge :>

**Comment by Dqnns** [comment]
Open a Pull Request! :)

[https://github.com/LabyMod/og-names/pulls](https://github.com/LabyMod/og-names/pulls)
[https://github.com/LabyMod/og-names/compare](https://github.com/LabyMod/og-names/compare)
