### ISSUE TITLE
Cashier

### ISSUE THREAD

**Issue by Cashier0101** [LabyMod/og-names#145]
IGN: Cashier

Link to show its OG: https://www.thefreedictionary.com/cashiers#:~:text=%EE%80%80cashier%EE%80%81.%20%28%20k%C3%A6%CB%88%CA%83%C9%AA%C9%99%29%20n.%201.%20a%20person%20responsible,any%20person%20responsible%20for%20handling%20cash%20or%20

**Comment by Cashier0101** [comment]
I am pretty sure this is OG and I think I should have the tag :D Thank you guys!

**Comment by potnet** [comment]
Denied, we currently don't have a semi list.

**Comment by Dqnns** [comment]
Hey, please open a Pull Request ! :)
