### ISSUE TITLE
OG badge dfl 

### ISSUE THREAD

**Issue by Simon4lorlg** [LabyMod/og-names#150]
Hi ich wollte mein acc dfl für denn OG badge Tag beantragen weil ich finde das es gut darein passt daszu ist dfl ein sehr gut benutztes und dazu bekanntes wort in der deutschen szene es ist eigentlich der komplette zu sammen bau von fussball hier ein link dazu 
https://www.dfl.de/de/

https://de.wikipedia.org/wiki/DFL_Deutsche_Fu%C3%9Fball_Liga      That is that

**Comment by WizardShops3044** [comment]
really good name matches the Og badge ;)

**Comment by TitenFighter1034** [comment]
So good name really good for Og badge ;) i like dfl name

**Comment by SheeShepp294** [comment]
I like this name is pretty good and good for the Og badge really name name for the tag ;) accept this this is really good

**Comment by Simon4lorlg** [comment]
Thx is really good for the Tag ;) ❤💜🤎🤎💜💙💚❤💕❣💗

**Comment by fiinjaaa** [comment]
the name dfl is very good for the og badge :D

**Comment by ffgyc** [comment]
creating 5 accounts to compliment yourself so embarassing

**Comment by Dqnns** [comment]
3 letters are not OG
