### ISSUE TITLE
add "moci" to the og name list

### ISSUE THREAD

**Issue by mochipooh** [LabyMod/og-names#17]
moci's are like mochis, but instead of a rice cake they are a bean cake (people often confuse them for mochis): https://steemit.com/food/@sak-a/moci-bean-cake-4f87ca5acc1db

moci is also a surname in some countries like in India and Nepal: https://forebears.io/surnames/moci

**Comment by Dqnns** [comment]
Agreed, create a Pull request.

**Moci**

**Comment by mochipooh** [comment]
> 

I don't really know how to make a pull request, I get stuck on the comparing part

**Comment by Dqnns** [comment]
I can add it to my pull requests if you want to.

**Comment by mochipooh** [comment]
> 

Yes please, that would be great :) thank you

**Comment by kiloxre** [comment]
Agreed

**Comment by orsou** [comment]
Has this been added/requested yet?

**Comment by 84** [comment]
Wouldn't this be semi-og? Its not even in the dictionary.

**Comment by mochipooh** [comment]
> 

Not at all. There are many words not in the dictionary, plus it depends on what dictionary you’re looking in. This food is often confused for a mochi. It’s most likely not been added to English dictionaries.

**Comment by mochipooh** [comment]
> Has this been added/requested yet?

I don’t think so

**Comment by 84** [comment]
> > 
> 
> Not at all. There are many words not in the dictionary, plus it depends on what dictionary you’re looking in. This food is often confused for a mochi. It’s most likely not been added to English dictionaries.

I am looking at the Merriam-Webster dictionary. It also isn't in the Oxford dictionary. The 2 most well known dictionaries.

**Comment by mochipooh** [comment]
> > > 
> > 
> > 
> > Not at all. There are many words not in the dictionary, plus it depends on what dictionary you’re looking in. This food is often confused for a mochi. It’s most likely not been added to English dictionaries.
> 
> I am looking at the Merriam-Webster dictionary. It also isn't in the Oxford dictionary. The 2 most well known dictionaries for the English language.

Bc once again it's not an english thing but it does indeed exist and a lot of other people know if it. and like I said before, it often gets confused for a mochi.

**Comment by mochipooh** [comment]
> 

^^^ it doesn't originate from the english language

**Comment by 84** [comment]
> > > Not at all. There are many words not in the dictionary, plus it depends on what dictionary you’re looking in. This food is often confused for a mochi. It’s most likely not been added to English dictionaries.
> > 
> > 
> > I am looking at the Merriam-Webster dictionary. It also isn't in the Oxford dictionary. The 2 most well known dictionaries for the English language.
> 
> Bc once again it's not an english thing but it does indeed exist and a lot of other people know if it. and like I said before, it often gets confused for a mochi.

Hate to break it to you but non english words are not included in this if you take a look at the nouns section

**Comment by mochipooh** [comment]
> > > > Not at all. There are many words not in the dictionary, plus it depends on what dictionary you’re looking in. This food is often confused for a mochi. It’s most likely not been added to English dictionaries.
> > > 
> > > 
> > > I am looking at the Merriam-Webster dictionary. It also isn't in the Oxford dictionary. The 2 most well known dictionaries for the English language.
> > 
> > 
> > Bc once again it's not an english thing but it does indeed exist and a lot of other people know if it. and like I said before, it often gets confused for a mochi.
> 
> Hate to break it to you but non english words are not included in this if you take a look at the nouns section

dude I didnt say that it's not ENGLISH. I said it doesnt orginate from english speaking places. This word is a word for a japanese food (or I think it's from nepal). It's a noun AND a sur name. https://forebears.io/surnames/moci  many other people agree with me that this is indeed an og, and I'm surprised it didn't have the og tag. Just because a word didn't originate from english speaking places, or isn't  too common in english speaking places doesn't mean its not og :)

**Comment by 84** [comment]
> > > > > Not at all. There are many words not in the dictionary, plus it depends on what dictionary you’re looking in. This food is often confused for a mochi. It’s most likely not been added to English dictionaries.
> > > > 
> > > > 
> > > > I am looking at the Merriam-Webster dictionary. It also isn't in the Oxford dictionary. The 2 most well known dictionaries for the English language.
> > > 
> > > 
> > > Bc once again it's not an english thing but it does indeed exist and a lot of other people know if it. and like I said before, it often gets confused for a mochi.
> > 
> > 
> > Hate to break it to you but non english words are not included in this if you take a look at the nouns section
> 
> dude I didnt say that it's not ENGLISH. I said it doesnt orginate from english speaking places. This word is a word for a japanese food (or I think it's from nepal). It's a noun AND a sur name. https://forebears.io/surnames/moci many other people agree with me that this is indeed an og, and I'm surprised it didn't have the og tag. Just because a word didn't originate from english speaking places, or isn't too common in english speaking places doesn't mean its not og :)

"dude I didnt say that it's not ENGLISH." then it would be in ANY english dictionary, would it not? It isn't.

**Comment by 84** [comment]
This isn't a noun. It isn't mentioned anywhere or in any dictionary. Infact, this is actually just the Indonesian word for "mochi". It isn't used in the English language or by any English speakers.

**Comment by bribes** [comment]
I wouldn't consider this "OG".

**Comment by Dqnns** [comment]
> I wouldn't consider this "OG".

Same, but I think "Mochi" would be actually, maybe in the foods folder. 🤔

**Comment by mochipooh** [comment]
> Has this been added/requested yet?

No it hasn't yet. Sorry for the late response :)

**Comment by mochipooh** [comment]
> 

Mochi and moci are almost the same things. Mochi is just way more common. moci is bean cake and mochi is a rice cake

**Comment by bribes** [comment]
> > I wouldn't consider this "OG".
> 
> Same, but I think "Mochi" would be actually, maybe in the foods folder. 🤔

Yeah, "Mochi" definitely but not "Moci".

**Comment by bribes** [comment]
> > 
> 
> Mochi and moci are almost the same things. Mochi is just way more common. moci is bean cake and mochi is a rice cake

Words on this list are suppose to be common.

**Comment by Dqnns** [comment]
Hey, please open a Pull Request ! :)
