### ISSUE TITLE
...

### ISSUE THREAD

**Issue by Jiaaaana** [LabyMod/og-names#18]
ok

**Comment by kiloxre** [comment]
yes You should add it as a og name ,

**Comment by kiloxre** [comment]
> Add Jiaana as a OG name, you can check google that it is og name
> -Thanks❤️

Yes They should add

**Comment by Dqnns** [comment]
That isn't a "OG" Name, not by any chance.

**Comment by 84** [comment]
Close issue

**Comment by orsou** [comment]
> Add Jiaana as a OG name, you can check google that it is og name -Thanks❤️

Please, if your username is not OG do not create GitHub accounts just to request that your own username gets added to the OG-Names list.

**Comment by orsou** [comment]
@Jiaaaana you don't have to edit the title and content of this issue, you can just close it! :)

**Comment by Dqnns** [comment]
O.o

**Comment by orsou** [comment]
@LabyStudio close this?
