### ISSUE TITLE
Add "Grumpy" to the og list

### ISSUE THREAD

**Issue by ghost** [LabyMod/og-names#19]
Could you add Grumpy, Sadness, and any other emotions you haven't added to the list yet? Ty!

**Comment by Dqnns** [comment]
Create a pull request...

**Comment by SynchedAlien** [comment]
no your account sucks

**Comment by orsou** [comment]
The person that opened this project deleted their account, you can go ahead and close this now.

**Comment by bribes** [comment]
Added this to my PR but is already included in the Emotions & Minecraft Terms PR

**Comment by Dqnns** [comment]
@bribes added this to #32.

_Issue can be closed_

**Comment by Dqnns** [comment]
#32

**Comment by Dqnns** [comment]
#32
