### ISSUE TITLE
Add "Slender" to the OG name list

### ISSUE THREAD

**Issue by Slendler** [LabyMod/og-names#25]
http://namemc.com/Slender

**Comment by orsou** [comment]
I agree "Slender" is definitely a very cool name (and a very cool guy too), you should create a pull request for it :)

**Comment by 84** [comment]
nice minecons

**Comment by niklaswa** [comment]
Maybe we can add a general list of popular video game characters

**Comment by Slendler** [comment]
> nice minecons

Thank you

**Comment by Slendler** [comment]
> Maybe we can add a general list of popular video game characters

Good idea

**Comment by orsou** [comment]
@Slendler do you want me to create a PR for your account?

**Comment by bribes** [comment]
Added this to my PR

**Comment by Slendler** [comment]
> @Slendler do you want me to create a PR for your account?

Ok 👍

**Comment by Dqnns** [comment]
@bribes added this to #32.

_Issue can be closed_

**Comment by Dqnns** [comment]
#32
