### ISSUE TITLE
OG Name Badge Change Recommendations

### ISSUE THREAD

**Issue by SynchedAlien** [LabyMod/og-names#3]
Add:
Blurt
Conner
Sentimental
Harlow

Remove:
Permanently

EDIT: I didn't realize how cayci was supposed to be pronounced, now I see why it has the badge.

**Comment by Dqnns** [comment]
I agree on Conner but Blurt isn't OG.

**Comment by SynchedAlien** [comment]
> I agree on Conner but Blurt isn't OG.

Blurt is definitely considered OG. It's a relatively commonly used English word. It may be low-tier, but if semis have the OG badge then it definitely should too. Blurt means to say something unexpectedly btw.

**Comment by kiloxre** [comment]
Agreed

**Comment by orsou** [comment]
> Add: Blurt Conner Sentimental Harlow
> 
> Remove: Permanently
> 
> EDIT: I didn't realize how cayci was supposed to be pronounced, now I see why it has the badge.

Create a pull request.

**Comment by bribes** [comment]
Added all of these to my PR

**Comment by Dqnns** [comment]
_Issue can be closed_

**Comment by Dqnns** [comment]
#32
