### ISSUE TITLE
add "Enragement" to the og badge list.

### ISSUE THREAD

**Issue by britisk** [LabyMod/og-names#31]
https://namemc.com/profile/Enragement.2

**Comment by orsou** [comment]
Create a PR.

**Comment by Dqnns** [comment]
Create a [Pull-Request ](https://github.com/LabyMod/og-names/compare) like @orsou said ^^.

`Issue can be closed`

**Comment by bribes** [comment]
I wouldn't consider this "OG".

**Comment by Dqnns** [comment]
Create a PR
