### ISSUE TITLE
Add "Lys" to OG Name Badge list.

### ISSUE THREAD

**Issue by LysMC** [LabyMod/og-names#43]
Lys
https://en.wikipedia.org/wiki/Lys
https://videnskab.dk/sporg-videnskaben/hvad-er-lys
https://ordnet.dk/ddo/ordbog?query=lys

**Comment by 84** [comment]
No.

**Comment by LysMC** [comment]
> No.

Yes

**Comment by 84** [comment]
Literally not even a word.

**Comment by LysMC** [comment]
> Literally not even a word.

Read the wiki.

**Comment by 84** [comment]
All of these are acronyms or random places/rivers no one has ever heard of.

**Comment by LysMC** [comment]
> All of these are acronyms or random places/rivers no one has ever heard of.

And names.

**Comment by 84** [comment]
Completely random names. Not a common name whatsoever. Stop being so desperate for some badge lmao

**Comment by LysMC** [comment]
> Completely random names. Not a common name whatsoever. Stop being so desperate for some badge lmao

It's a submission.

**Comment by 84** [comment]
and it will not be added so please do close your issue

**Comment by LysMC** [comment]
> 

no.

**Comment by Dqnns** [comment]
So. In terms of value, Lys is not particularly expensive or anything. In my opinion, it is not an "OG", but a pronounceable 3 letter.

_Personally, I don't like it when people come in and just add their name._

**Comment by bribes** [comment]
Man's rlly said no. 🤣 🤡

**Comment by Dqnns** [comment]
_Mar 30, 2022_
