### ISSUE TITLE
Add "Arbitrar" on the OG name list.

### ISSUE THREAD

**Issue by Inventical** [LabyMod/og-names#44]
https://en.wiktionary.org/wiki/arbitrar
https://dictionary.cambridge.org/dictionary/portuguese-english/arbitrar

If someone could add this to their pull request that would be great.

**Comment by cyromaniac** [comment]
I agree, this name should be added on the OG list.

**Comment by 84** [comment]
I disagree. It is not a English word nor is it well known.

**Comment by Dqnns** [comment]
This isn't "OG"
