### ISSUE TITLE
Add "Betrothal'' to OG list.

### ISSUE THREAD

**Issue by Duspielen** [LabyMod/og-names#48]
https://namemc.com/profile/betrothal.4
https://en.wikipedia.org/wiki/Engagement#Betrothal
https://www.deepl.com/en/translator#en/ru/betrothal
https://www.merriam-webster.com/dictionary/betrothal
![image](https://user-images.githubusercontent.com/92799173/161510648-0257f5df-fbe1-4a2a-a842-1a9024ea7822.png)

**Comment by rapust** [comment]
> 

yes

**Comment by Dqnns** [comment]
I think engaged is the better word for this.

**Comment by TheQuiu** [comment]
I think this name agreed for OG

**Comment by orsou** [comment]
Definitely not OG.

**Comment by 84** [comment]
Not gonna front. This is the worst "OG" name I have ever seen lmaoo. So many people desperate to get their semis/random names this badge.

**Comment by SynchedAlien** [comment]
> Not gonna front. This is the worst "OG" name I have ever seen lmaoo. So many people desperate to get their semis/random names this badge.

Yeah, I don't think this deserves it
