### ISSUE TITLE
Issue with cleanup.py

### ISSUE THREAD

**Issue by bribes** [LabyMod/og-names#54]
I'm not too familiar with Python but there is a bug I am experiencing which causes words to be merged to one line like, "shutdownsick" when adding the word shutdown.

**Comment by bribes** [comment]
Seems to happen when adding the word after where the word is suppose to be because when I add the word to the very end of the word document the word gets added to the same line.

Ex.
Apple
Area
Clear
Duck
*Aim*

When cleanup.py is ran, this would turn into:

Apple
AreaAim
Clear
Duck

**Comment by Dqnns** [comment]
@LabyStudio

**Comment by Dqnns** [comment]
@bribes, can I close this?

**Comment by bribes** [comment]
> @bribes, can I close this?

Uh ok…
