### ISSUE TITLE
Add idfc" to og list

### ISSUE THREAD

**Issue by Ass1stantM3lody** [LabyMod/og-names#56]
idfc (i dont fu**ing care) is very commion phrase

**Comment by fez6** [comment]
Not an OG.

**Comment by Ass1stantM3lody** [comment]
Yes it is

**Comment by Ass1stantM3lody** [comment]
It's just like stfu or sth

**Comment by bribes** [comment]
This will probably be adding if or when we make a abbreviations.txt.

**Comment by fez6** [comment]
> This will probably be added if or when we make a abbreviations.txt. Not sure if we will make one though and it's not a guarantee that it'll be added maybe it'll just be the common ones like wtf, lol, etc.

I would not really consider abbreviations OG, some very popular abbreviations sure, but not evey random abbreviation.

**Comment by bribes** [comment]
> 

I agree 👍

**Comment by fez6** [comment]
I created a pull request for abbreviations (#58) we can discuss there what kind of abbreviations count as OG, maybe "idfc" counts.

**Comment by Dqnns** [comment]
#58
