### ISSUE TITLE
API endpoint not working properly

### ISSUE THREAD

**Issue by fez6** [LabyMod/og-names#63]
I know this is not related directly to the og-names repository **but** since there is no repository for the laby.net site nor the API I will just report it here.

The `https://laby.net/api/server/{server}/rates` endpoint works just fine but the `https://laby.net/api/server/{server}/rates/{uuid}` endpoint just gives the same response as `https://laby.net/api/server/{server}/rates`.

**Examples:**
* [API request without UUID](https://laby.net/api/server/gommehd.net/rates)
* [API request with UUID](https://laby.net/api/server/gommehd.net/rates/e0276ad9-1cd6-4c8d-b8f7-ff97e75c5982)

**Comment by bribes** [comment]
It seems like everything after /rates is ignored.

**Comment by LabyStudio** [comment]
Should be fixed.

You can report issues on our LABYnet [Discord](https://discord.gg/laby)
