### ISSUE TITLE
Add Headquarter To OG Tag

### ISSUE THREAD

**Issue by HeadquarterLOL** [LabyMod/og-names#67]
I couldn't open a Pull Request but Headquarter Should be added to the og list 

https://www.merriam-webster.com/dictionary/headquarter?msclkid=b17f8151d08411ecb15be115cdad1326
https://www.thefreedictionary.com/headquarter?msclkid=818d040fd08211ecb01c83fddb76e958
Thanks for reading

**Comment by Dqnns** [comment]
Create a [PR](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/working-with-your-remote-repository-on-github-or-github-enterprise/creating-an-issue-or-pull-request)
