### ISSUE TITLE
add "Xenophya" to OG badge list.

### ISSUE THREAD

**Issue by britisk** [LabyMod/og-names#68]
xenophya
Also found in: [Wikipedia](https://encyclopedia.thefreedictionary.com/xenophya).
xenophya (zɛˈnɒfɪə)
n
parts of a shell or skeleton formed by foreign bodies
Collins English Dictionary – Complete and Unabridged, 12th Edition 2014 © HarperCollins Publishers 1991, 1994, 1998, 2000, 2003, 2006, 2007, 2009, 2011, 2014

**Comment by Dqnns** [comment]
wouldn't say this is OG

**Comment by 84** [comment]
No.

**Comment by Dqnns** [comment]
not og
