### ISSUE TITLE
add "Aleko" to OG Badge list

### ISSUE THREAD

**Issue by Aleko1243** [LabyMod/og-names#69]
Hi everyone!

I was surprised that this name is not already on the list but,
"Aleko" is a well known calling for the name "Alexander" in many parts of souther europe.

https://i.imgur.com/gkUwHnG.png
https://www.beliebte-vornamen.de/12874-aleko.htm#:~:text=Aleko%20ist%20eine%20bulgarische%20Kurzform,%E2%80%9Eder%20Verteidiger%E2%80%9C%20gedeutet%20werden.

I really feel like this should have the OG tag because of it's popularity.
Thanks!

**Comment by 84** [comment]
I would not say so.

**Comment by Aleko1243** [comment]
Why is that? Don't you think that the name is valid? I could try finding more sources to post here if you like that.
