### ISSUE TITLE
Osterei & Kuscheltier

### ISSUE THREAD

**Issue by KarmaBait** [LabyMod/og-names#76]
Requested by users:

Osterei & Kuscheltier

Osterei: https://www.duden.de/rechtschreibung/Osterei
Kuscheltier: https://www.duden.de/rechtschreibung/Kuscheltier

**Comment by shrobbyy** [comment]
Disagree. It should be restricted to English words.

**Comment by 84** [comment]
Shouldn't be added

**Comment by Dqnns** [comment]
Not OG :/
