### ISSUE TITLE
Add "Toss" to the OG list

### ISSUE THREAD

**Issue by rockstarmade999** [LabyMod/og-names#80]
https://www.merriam-webster.com/dictionary/toss

https://www.dictionary.com/browse/toss

Word is commonly used in many sports.

**Comment by 84** [comment]
Yes

**Comment by Dqnns** [comment]
Open a PR ^^

**Comment by Dqnns** [comment]
@rockstarmade999, good OG!

Create a [PR](https://github.com/LabyMod/og-names/pulls) !
