### ISSUE TITLE
Add  Eluisa & Millvina 

### ISSUE THREAD

**Issue by yariquv3** [LabyMod/og-names#94]
Source:
https://www.vorname.com/name,Eluisa.html

https://en.wikipedia.org/wiki/Millvina_Dean

**Comment by 101OG** [comment]
Those are both first names, in my opinion those names deserve an OG page.

**Comment by Eiskxlt** [comment]
Sure they are Firstnames so they Deserve the OG-Badge

**Comment by Dqnns** [comment]
Not every first name is automatically an "OG" Name...

Eluisa is okay, kinda "Semi-OG" tho.

Millvina isn't "OG" at all.
