### ISSUE TITLE
Known First Names & Last Names

### ISSUE THREAD

**Issue by 101OG** [LabyMod/og-names#96]
The two names definitely deserve the OG page :
The Name: Ahamad
Ahamad is a very common surname and also known as a common first name.
: https://forebears.io/search?q=Ahamad&meaning=genealogy-names-surnames
: [ᐅ Vorname Ahmad: Bedeutung, Herkunft, Namenstag & mehr ...](https://www.kinderinfo.de/vornamen/jungen/ahmad/)
: https://de.wikipedia.org/wiki/Ahmad
The Name: Abakar
Abakar is a very common surname and also known as a common first name.
: https://forebears.io/search?q=Abakar&meaning=genealogy-names-surnames
: [Abakar | Bedeutung, Verbreitung, Sozialprestige](https://vornamen.blog/Abakar)
: https://de.wikipedia.org/wiki/Abakar

**Comment by Dqnns** [comment]
I would not describe Ahamad as "OG", rather Ahmad, but the name already has an OG tag.

Abakar is completely unknown to me...

**Comment by 101OG** [comment]
Hello,
Just got back from work and saw this message. I want to say something about
that, of course the names Ahamad/Abakar are not known in the German region,
but they are known in other countries. therefore OG. Thank you very much
and I hope I have convinced you with this. If you have any questions about
the names (surnames) Ahamad/Abakar, you can write to me at any time.

**Comment by 101OG** [comment]
> Ich würde Ahamad nicht als „OG“ bezeichnen, eher Ahmad, aber der Name hat schon ein OG-Tag.
> 
> Abakar ist mir völlig unbekannt...

**Comment by NeroUwU** [comment]
Hello Dennis!
You stated, that the names "Akabar and Ahamad" are not OG-Tag Worthy. I Would like to refer to that and give you some infos.
After a little research, i found out that these names are used  in Germany, India and several other countries. It is used as both, First and Last name. I agree,
 Ahamad seems to be a pretty uncommon name. That is why it is no where to be found on sites like "Wikipedia..." but to show you that there are Sites that do list  them
, i linked you a few sites. 

Thank you and have a great Day
Nero
-> https://de.namespedia.com/details/Ahamad
- >https://www.ancestry.com/name-origin?surname=ahamad
- >https://de.wikipedia.org/wiki/Akbar (Bearbeitet)

**Comment by NeroUwU** [comment]
Hello Dennis!
You stated, that the names "Abakar and Ahamad" are not OG-Tag Worthy. I Would like to refer to that and give you some infos.
After a little research, i found out that these names are used  in Germany, India and several other countries. It is used as both, First and Last name. I agree,
 Ahamad seems to be a pretty uncommon name. That is why it is no where to be found on sites like "Wikipedia..." but to show you that there are Sites that do list  them
, i linked you a few sites. 

Thank you and have a great Day
Nero
-> https://de.namespedia.com/details/Ahamad
- >https://www.ancestry.com/name-origin?surname=ahamad
- >https://de.wikipedia.org/wiki/Abakar

**Comment by Eiskxlt** [comment]
The Name: Ahamad
Why ? : Because Its a Name like any other so I deserves the OG-Badge

**Comment by Dqnns** [comment]
> Hello Dennis! You stated, that the names "Abakar and Ahamad" are not OG-Tag Worthy. I Would like to refer to that and give you some infos. After a little research, i found out that these names are used in Germany, India and several other countries. It is used as both, First and Last name. I agree, Ahamad seems to be a pretty uncommon name. That is why it is no where to be found on sites like "Wikipedia..." but to show you that there are Sites that do list them , i linked you a few sites.
> 
> Thank you and have a great Day Nero -> https://de.namespedia.com/details/Ahamad
> 
> * > https://www.ancestry.com/name-origin?surname=ahamad
> * > https://de.wikipedia.org/wiki/Abakar

It doesn't matter if the name is one Wikipedia, a first name or in the dictionary.

**Comment by SaimTR** [comment]
thats actually cool name , known as Abakar Sylla footballer from chad
